import Head from "next/head";
import { SignInButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";
import Link from "next/link";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "Matrice AI!" });
  const user = useUser();

  return (
    <>
      <Head>
        <title>Panels</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-center">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Panels
          </h1>
          <h3 className="text-2xl font-extrabold sm:text-[5rem]">
            Tables for Interview Management
          </h3>
          <p className="text-2xl">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <div className="text-2xl">
            {user.isSignedIn? "Hello " + user.user.fullName + "!" : <SignInButton/>}
            <br/>
            <br/>
            {user.isSignedIn? <Link href={'/dashboard'} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mb-2 rounded" >Go to Dashboard</Link> : ""}
          </div>
        </div>
      </main>
    </>
  );
}
