import Head from "next/head";
import { SignInButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "Matrice AI!" });

  return (
    <>
      <Head>
        <title>Panels</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#57b9b7] to-[#2a2f8b]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-center">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Panels
          </h1>
          <h3 className="text-2xl font-extrabold text-white sm:text-[5rem]">
            Tables for Interview Management
          </h3>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <div className="text-2xl text-white">
            <SignInButton />
          </div>
        </div>
      </main>
    </>
  );
}
